name: my_notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - numpy
  - pandas
  - scikit-learn
  - keras
  - nltk
  - matplotlib
  - seaborn
  - watermark
  - tqdm
  - joblib
  - tpot
  - beautifulsoup4
  - pip:
    - twitter
    - googlemaps
